const validationErrors = {
  nameRequired: 'Sorry! the full name field is required',
  quantityError: 'The quantity of an item must be a number greater than zero',
  validNumber: 'Please your phone number can only contain numbers and cannot be greater than 15 or less than 8 characters',
  phoneRequired: 'Sorry! the phone number field is required',
  nameLength: 'Sorry your fullname cannot be less than 8 characters and must contain a space',
  validName: 'Please enter a valid full name. Your full name can only contain letters and spaces',
  addressRequired: 'Sorry, the Address field is required',
  addressLength: 'Sorry, your address cannot be less than 10 characters',
  emailRequired: 'Sorry, the Email field is required',
  validAddress: 'Please enter a valid Address',
  validEmail: 'Please enter a valid email address',
  validStatus: 'Please enter a valid status. The status can only be Canceled or Declined or Accepted or Completed',
  itemsEmpty: 'Sorry, your order is invalid. You did not pick any items?',
  validItems: 'Sorry, the items are invalid. Valid items must be objects.',
  validOrderId: 'Please the orderId must be a number greater than zero',
  validUserId: 'Please the userId must be a number greater than zero',
  emptyStatus: 'Sorry, the status is required',
  passwordEmpty: 'Your password is required',
  validPassword: 'Sorry, your password cannot contain spaces.',
  passwordLength: 'Sorry, your password must not be less than 8 characters',
  validRole: 'Invalid user role. The role can only be the values: 0, 1 or 2 ',
  emailExists: 'Sorry, this email address has already been registered',
  noOrder: 'Sorry, no order has been placed yet.',
  noOrders: 'Sorry, no orders have been placed yet.',
  mealRequired: 'Sorry, the name of the meal is required',
  validMeal: 'Please enter a valid meal name. It can only contain letters and spaces',
  mealLength: 'Sorry, the name of the meal must not be less than 5 characters or more than 50',
  descRequired: 'Sorry, the description of the meal is required',
  validDesc: 'Sorry, the description of the meal must be a string of alphanumeric, and special characters and must start with a letter',
  descLength: 'Sorry, the description of the meal must not be less than 30 or more than 255 characters',
  priceRequired: 'Sorry, the price of the meal is required.',
  validPrice: 'Sorry, the price can only be positive numbers greater than 0',
  mealExists: 'Sorry, either the name or description of this meal exists. They cannot be duplicates.',
  validMealId: 'Please the mealId must be a number greater than zero',
  noMeal: 'Sorry, There is no meal for the mealId you supplied.',
  noEmail: 'Sorry this email address has not been registed. Click the link below to register',
  loginFailure: 'Could not login. The email and password do not match',
  loginRequired: 'Sorry, both your username and password are required',
  notAllowed: 'Sorry, you are not authorized to access this section of the app. Login with your username and password to have access',
  notAuthenticated: 'Sorry, you have to be logged in to access the features in this section of the app.',
  noMenu: 'Sorry no meal has been added to the menu yet.',
  noOrderId: 'Sorry, There is no order for the orderId you supplied.',
  noUserOrder: 'Sorry, this user has not placed any order',
  duplicateEditMeal: 'Sorry, the meal could not be updated. Either the description or name you supplied for the meal already exists in the database or you did not change anything.',
  noUsers: 'Sorry, no users have been registered yet',
  picRequired: 'Sorry! the url to for the meal image is required',
  validPic: 'Please enter a valid url for the meal image',
};

export default validationErrors;
